services:
  app:
    container_name: floww-backend
    build:
      context: .
      secrets:
        - package_registry_token
    volumes:
      - ./app:/home/appuser/app
    command: >
      python -X frozen_modules=off -m debugpy --listen 0.0.0.0:3100 -m uvicorn app.main:app --host 0.0.0.0 --reload
    environment:
      LOG_FORMAT: console
    ports:
      - "8000:8000"
      - "3100:3100"
    env_file:
      - .env
  

  db:
    container_name: floww-backend-db
    image: postgis/postgis:17-3.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgis
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret

  centrifugo:
    container_name: floww-backend-centrifugo
    image: centrifugo/centrifugo:v6
    command: centrifugo -c /centrifugo/config.json
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    ports:
      - "5001:8000"  # WebSocket and HTTP API
      - "8001:8001"  # Admin panel
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  migrations:
    container_name: "floww-backend-migrations"
    build:
      context: .
      secrets:
        - package_registry_token
    command: "python -m alembic upgrade head"
    env_file:
      - .env
    restart: no



secrets:
  package_registry_token:
    environment: GL_PAT